name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: ./build.sh main
    - name: Test Docker Image
      run: docker image ls django-basin3d | grep -v TAG | head -1  | awk  '{{ print $1":"$2 }}' | xargs ./runTests.sh

